// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://jgsgxjpzqdakuhlpyise.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnc2d4anB6cWRha3VobHB5aXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4NzE2MTYsImV4cCI6MjA0NjQ0NzYxNn0.RG8hcFFj0AdEBsIDqem7-5HMcm8PxN9-qxPffFnRubA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);